@HOST = https://api-taskvault.onrender.com

@USERID = f336a54f-dab2-403c-89f6-2d1ccc1a0d09

PUT {{HOST}}/user/{{USERID}} HTTP/1.1
Content-Type: application/json

{
    "name": "Felipe",
    "email": "felipe@123",
    "password": "456789"
}