@HOST = https://api-taskvault.onrender.com

@USERID = 828cbcad-d760-4a50-a0ad-f4cf216df893

PUT {{HOST}}/user/{{USERID}} HTTP/1.1
Content-Type: application/json

{
    "name": "Felipe",
    "email": "fbryan@123",
    "password": "abcdef"
}